import './globals.css'

// title
export const metadata = {
  title: 'Create nohssam',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          <li><a href='/read/1'>HTML</a></li>
          <li><a href='/read/2'>CSS</a></li>
          <li><a href='/read/3'>JS</a></li>
        </ol>
        {children}
        <ul>
          <li><a href='/create'>Create</a></li>
          <li><a href='/update/1'>Update</a></li>
          <li> <input type='button' value="delete"/></li>
        </ul>
      </body>
    </html>
  )
}
